language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sanp/multi-c-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanp/multi-c-test npm test

after_success:
  - docker build -t sanp/multi-c-client ./client
  - docker build -t sanp/multi-c-nginx ./nginx
  - docker build -t sanp/multi-c-server ./server
  - docker build -t sanp/multi-c-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sanp/multi-c-client
  - docker push sanp/multi-c-nginx
  - docker push sanp/multi-c-server
  - docker push sanp/multi-c-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-eu-central-1-379144642287
  bucket_path: multi-container
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY